### ISSUE TITLE
bug/to-read-div-weird

### ISSUE THREAD

**Issue by jecoc0** [BryceStockman/personal-library-tracker#25]
In one of the recent merge requests (#22), it looks like the div for the first section/outer section might have been messed up. This might have had to do with the closing div tags I asked @Oatbanger to delete
<img width="616" alt="Screen Shot 2021-12-03 at 8 44 28 PM" src="https://user-images.githubusercontent.com/81825125/144695727-1646ba83-a275-4e30-b410-c133324b60f7.png">
.

**Comment by Oatbanger** [comment]
At least we know exactly which commit to revert!
