### ISSUE TITLE
HTML Skeleton

### ISSUE THREAD

**Issue by BryceStockman** [BryceStockman/personal-library-tracker#3]
Acceptance Criteria:
- Well organized semantic tags outlining the structure of the page
- HTML Attributes that enable JS and CSS to target specific tags and elements of the HTML to style and dynamically insert our added books
- bootstrap
- modal for books to add
- CSS links and JS script tags added
- CSS and JS files organized and structured for ease of use

**Comment by jecoc0** [comment]
![layout example](https://user-images.githubusercontent.com/81825125/144172279-390bec84-5790-4d63-a92d-2dbe45c2ab66.jpg)

![Modal view](https://user-images.githubusercontent.com/81825125/144172314-d7d9e6c1-59ec-44db-9b13-bc4fac310102.jpg)

**Comment by BryceStockman** [comment]
Thanks for sending, I can definitely work with this!

**Comment by Oatbanger** [comment]
@jecoc0 Thanks so much for getting this up. Quick question, right now I don't see a container to add a book or logically link to the modal. Do you have any input on how we should link the two? Can we possible add this to the wireframe?

**Comment by BryceStockman** [comment]
Cameron,
Instead of the links in the top right add a search bar with a label to
‘search books’ or something like that.

**Comment by BryceStockman** [comment]
Pretty sure this is done, closing this issue.
